// Licensed to Elasticsearch B.V. under one or more contributor
// license agreements. See the NOTICE file distributed with
// this work for additional information regarding copyright
// ownership. Elasticsearch B.V. licenses this file to you under
// the Apache License, Version 2.0 (the "License"); you may
// not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

// Code generated by beats/dev-tools/cmd/asset/asset.go - DO NOT EDIT.

package include

import (
	"github.com/elastic/beats/libbeat/asset"
)

func init() {
	if err := asset.SetFields("cartobeat", "fields.yml", Asset); err != nil {
		panic(err)
	}
}

// Asset returns asset data
func Asset() string {
	return "eJzUWFtvGzcTffevGPjl+wrIi8ZujEIPRVOnaIzWbdAkT0WhjMjRijWX3JBcS+qvL3jZm3Z1i1W01YPh5eWcQ3LmDHcvruCRNlOYE7oLACecpCl8F584WWZE6YRWU/jmAgDgTiuHQllguii0CvNgIUhyC/iEQuJcEggFKCXQEykHblOSzS4gDZteBKArUFhQJM78v6F1lNP/3i8pTAC9ALekoBAsKS5UHhqkzqEgazEnm8F9Z1SYJmwDZcl5gb6fabUQeWXQ08FCSJr4dt+JDp5QVn4mVJZ4wBTOPyrtumBhCiy1dYkpjX+vA1VPx8T3haaP/vFjg6PDinfryoabVjMe3rhGG1ow5CqjiMN8E6h0SZ5G5WA31lEBWsFqKdiyFd7ZO1MpJVQ+osaJgv7U6gg19ci/U80TGSu0OiwmDazDKoRzOPyclJdCHNxS2BjKWT90L7/1S7EOi/IygfpYnwJHV++DoU+VMMSn4ExVNy60KdD1xtEai9Kn3qsqr6yD61u3hOsvX9xO4MX19Obl9OVNdnNzfdzuBkmwioFMKQ19ghhi2nBYoW3Xt7Uoh7ndz/LKzIUzaDZhbNwtht4KQryXZOJBoeLhwRlUFplrzyPu0xZxdIfePur5H8TqXIsPs9jzSJuVNny/0MarKkumzSlvUJFsSwEZo01PQG50Ve4n+d5Pqh2QRUYfv8i58GNRglAL7TOboQ3+FXhsVgdDcsUasFaTzKxprzU5WrtO4w5ZrbSEkw0ImOZDdKlVfgq6BxlCe6wBdP/MjkKPYZJKFJO64m2NuvOPUBr9JDj5ZTrk6HC8bD2kXlgYXUSkZqr1Z9VaEHI+CwNmNaQfychabXZWMT80C7OyGnY7sYkdyN6fO+WtrzCDt9pa4QM31CQLaMgDTiBnNAFtgItcOJSaEapspzahrEPFaCYOpM59Ggj3r2tJvohAgWwp1HbqjjEcrkwNR7euH8eSBsw6cdbss7vOCuKiKvazP0SIEGKnkadrjpDCbWadktcoqOwVoXVXL9gBI+0AQaiIoq12wkY5wrZlbk/IBW9sTrWRknqu1seHXpritfygdS4pZtpudkP5wVL7axhzaH0p0blmjyF/Uqa/rp9HwGMfWIfO26+UxHzNDmke+3zO2qU2bhYrwBQWKK0/NFRsqU3Nd9Vk+UXflOslN7JgtD7s8vFUE8hkgj/PEz8o8amiFhAEH3P1hq4YKx8nMXbjIsDVt9MkwF8k5pWQDrTaJ6VjBp+p5K7h9Fj7uCTOSdoBW+8uAfvvEwe03IediDxN0PpgbkP2TXwaAbn3l4FOoPoqN7CeNjZ9+8HITNynxeXzz+RNeq0YnsaZIj0axEiQo2FL4Yi5ypxhDT04+D9leQbrr29nt19NAE0xgbJkEyhEab8YStE2KyU6f6V/npJf3kENlDQwUk7bCVTzSrlqAiuhuF7tENF/4/l8DQlnlGOBhZCbZ1NEmLRIQ3yJbgKc5gLVBBaGaG75vtWKciCh17SH/SdhnTe0+7dXyLkha8kOCQpkz1tkTbNEw1doqCWbQGUrlHIDD6/uuhpqH3ms5mQUObKtm/zYbRuhbfuba3D/TtuCQtdL9pfFdtJBA+qJhpNsqNT8DOWhswOl5tHbRqmq51pTh+mt5vDh/vWQyP+1JbLzLapFHJL5N7Cz7qBH3LGFxxbX44giGhRYDplQKe3C96+z0XUgxznPeWHp8LLe3WUf7RmubKO8ETc5jFx33qIv5ZpfjrsKrUsyoiDlUP72e5Qt1xwKzStJO5wggsMpX1D8jcgU8VMnKh7u8sI6wSzgXFfOY/7PAjInnjqXzyM+oBTaDKtVV9GBvXwICN5TjWDdMNym7M2q+autzze7JRyQ0ZESMOPbTrY1ZlvTthynHcpB747vPg1o+lI537TefoJq/3vvedNhjO5Jx6AJH/8BhQ+43q2v1mZXuH1kn32Y71ZYdo/yP3WSfiP+9cc5FPlXAAAA//84mZ7d"
}
